AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'
    - 'exe/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120